#!/usr/bin/env python3

"""
Produces a table of
design_id,  non-compatible products in any design,  max_compat
for the designs in a given result directory

"""

import argparse
import glob
import pandas as pd
import re
from general import find_n_prods

def main():
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('pf_dir', help='Path to directory with modcell output pareto front .csv input files')
    parser.add_argument('-t','--threshold', help='Compatibility threshold', default=0.5, type=float)
    args = parser.parse_args()

    fnames = glob.glob("{}*.csv".format(args.pf_dir))
    fnames.sort()

    n = find_n_prods(fnames[0])
    print("design_id,non_compatible_products,maximum_compatibility(%)")
    for pf_path in fnames:
        df = pd.read_csv(pf_path)
        iscompat = df[df.columns[df.columns.str.contains("objective")]] >= args.threshold
        print(re.sub('.*/([a-z,A-Z]+-[0-9]+-[0-9]+).*', r'\1',pf_path),
                ',',
                '|'.join([re.sub('(.*)\(objective\)',r'\1',x) for x in iscompat.columns[iscompat.sum(0) == 0].tolist()]),
                ',',
                '{0:.0f}'.format((iscompat.sum(1).max()/n)*100))

if __name__ == '__main__':
   main()
