#!/usr/bin/env python3

""" Print a subset of designs. E.g., to print the designs with solution indices 2, 33 , and 50: `getsubset.py <pf_path> [2,33,50] <output_path>` If you would like to use spaces in the list surround it by strings. """

import argparse
import pandas as pd
import ast

def main():
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('pf_path', help='Path to modcell output pareto front .csv input file')
    parser.add_argument('design_list', help='List of solution indices to extract, e.g. [1,2,10] or \"[1, 2, 10]\"')
    parser.add_argument('output_path', help='Name of file to write subset')
    args = parser.parse_args()

    df = pd.read_csv(args.pf_path)
    df = df.set_index('Solution index')
    df = df.loc[ast.literal_eval(args.design_list), :]
    df.to_csv(args.output_path)

if __name__ == '__main__':
   main()
